### ISSUE TITLE
Report's README.md - Broken links

### ISSUE THREAD

**Issue by MatiasMFM2001** [l-zeuch/lagpdb-cc#43]
**Describe the bug**
Inside the `Author, License, and Disclaimer` topic, both hyperlinks are broken. GitHub reports 404 error

**To Reproduce**
1. Go to the [README.md](https://github.com/l-zeuch/lagpdb-cc/blob/master/moderation/Report-System/README.md#author-license-and-disclaimer) file
2. Click on `l-zeuch` and `license agreement` links
3. See error in both cases

**Expected behavior**
First link, see your user profile? Second one, no idea

**Comment by l-zeuch** [comment]
Thanks for reporting this!
Will push a fix when I get home.

**Comment by MatiasMFM2001** [comment]
You're welcome!
