### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Futureslinky** [l-zeuch/lagpdb-cc#44]
**Describe the bug**

**To Reproduce**

Just try making the report command again.

**Expected behavior**
The embed is supposed to change.

**Screenshots**
![image](https://user-images.githubusercontent.com/77411358/127758235-3b927ab5-c012-4d2c-afae-6547abc8ac77.png)

**Additional context**
I am getting that error, and the cause of this error is my reaction code.

Sorrry I haven't explained clearly, its 12 am and I am trying to get some sleep.

**Comment by l-zeuch** [comment]
README says what to do, run the `report dbSetup` command.

**Comment by dskarasev** [comment]
Hi!
I have setup the script as described in README and have the same issue. This error message appears on trying to run **-report dbSetup** command

Here is the screensho
<img width="793" alt="Снимок экрана 2021-10-03 в 02 09 24" src="https://user-images.githubusercontent.com/10157151/135734033-1a2ddf42-04ab-4a0a-baea-7946ee30bceb.png">
t

**Comment by dskarasev** [comment]
> README says what to do, run the `report dbSetup` command.

Hi l-zeuch. As I tried to describe in #48 here is no clean solution for this issue. The error appears exactly for `report dbSetup` command which you offer as a solution.

**Comment by l-zeuch** [comment]
It's saying that you did not set the trigger to match the server's prefix, that's why it is complaining. The second error is cascading from the first error.
